version: "2"
linters:
  default: all
  disable:
    - bodyclose
    - containedctx
    - contextcheck
    - cyclop
    - dupl
    - dupword
    - err113
    - errchkjson
    - exhaustive
    - exhaustruct
    - forcetypeassert
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - gocyclo
    - gomodguard
    - gosec
    - inamedparam
    - ireturn
    - lll
    - maintidx
    - makezero
    - mnd
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - noinlineerr
    - nonamedreturns
    - paralleltest
    - perfsprint
    - prealloc
    - rowserrcheck
    - sqlclosecheck
    - tagalign
    - tagliatelle
    - testpackage
    - tparallel
    - usestdlibvars
    - varnamelen
    - wrapcheck
    - wsl
    - wsl_v5
  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: github.com/instana/testify
              desc: not allowed
            - pkg: github.com/pkg/errors
              desc: Should be replaced by standard lib errors package
    forbidigo:
      forbid:
        - pattern: ^print(ln)?$
        - pattern: ^spew\.Print(f|ln)?$
        - pattern: ^spew\.Dump$
    funlen:
      lines: -1
      statements: 135
    goconst:
      ignore-tests: true
      min-len: 3
      min-occurrences: 4
    godox:
      keywords:
        - FIXME
    govet:
      disable:
        - fieldalignment
      enable-all: true
    misspell:
      locale: US
    revive:
      rules:
        - name: struct-tag
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: exported
        - name: if-return
        - name: increment-decrement
        - name: var-naming
        - name: var-declaration
        - name: package-comments
          disabled: true
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: indent-error-flow
        - name: errorf
        - name: empty-block
        - name: superfluous-else
        - name: unused-parameter
          disabled: true
        - name: unreachable-code
        - name: redefines-builtin-id
  exclusions:
    generated: lax
    rules:
      - linters:
          - funlen
          - goconst
          - godot
        path: (.+)_test.go
      - linters:
          - unparam
        path: (.+)_test.go
        text: ' always receives '
      - path: (.+)\.go$
        text: Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*print(f|ln)?|os\.(Un)?Setenv). is not checked
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax